export const possibleAnswersForNonChordates = {
  "Specialized tissues": ["None", "Present"],
  "Body plan symmetry": ["Asymmetry", "Bilateral", "Radial"],
  "Embryonic cell layers": ["None", "Diploblastic", "Triploblastic"],
  Coelom: ["Acoelomate", "Pseudocoelomate", "Eucoelomate"],
  "Embryonic development": ["Absent", "Protostome", "Deuterostome"],
  "Digestive system": ["None", "One-way", "Two-way"],
  Segmentation: ["Absent", "External", "Internal", "Both"],
  Cephalization: ["None", "Present", "Both"],
  Motility: ["Non-motile", "Motile", "Sessile"],
  Molting: ["Absent", "Present"],
};

export const nonChordateData = {
  Porifera: {
    "Specialized tissues": "None",
    "Body plan symmetry": "Asymmetry",
    "Embryonic cell layers": "None",
    Coelom: "Acoelomate",
    "Embryonic development": "Absent",
    "Digestive system": "None",
    Segmentation: "Absent",
    Cephalization: "None",
    Motility: "Non-motile",
    Molting: "Absent",
  },
  Cnidaria: {
    "Specialized tissues": "Present",
    "Body plan symmetry": "Radial",
    "Embryonic cell layers": "Diploblastic",
    Coelom: "Acoelomate",
    "Embryonic development": "Absent",
    "Digestive system": "Two-way",
    Segmentation: "Absent",
    Cephalization: "None",
    Motility: "Motile",
    Molting: "Absent",
  },
  Platyhelminthes: {
    "Specialized tissues": "Present",
    "Body plan symmetry": "Bilateral",
    "Embryonic cell layers": "Triploblastic",
    Coelom: "Acoelomate (acoelom)",
    "Embryonic development": "Protostome",
    "Digestive system": "One-way",
    Segmentation: "Absent",
    Cephalization: "Present",
    Motility: "Motile",
    Molting: "Absent",
  },
  Rotifera: {
    "Specialized tissues": "Present",
    "Body plan symmetry": "Bilateral",
    "Embryonic cell layers": "Triploblastic",
    Coelom: "Pseudocoelomate",
    "Embryonic development": "Protostome",
    "Digestive system": "One-way",
    Segmentation: "External",
    Cephalization: "Present",
    Motility: "Motile",
    Molting: "Absent",
  },
  Annelida: {
    "Specialized tissues": "Present",
    "Body plan symmetry": "Bilateral",
    "Embryonic cell layers": "Triploblastic",
    Coelom: "Eucoelomate",
    "Embryonic development": "Protostome",
    "Digestive system": "One-way",
    Segmentation: "Both",
    Cephalization: "Present",
    Motility: "Motile",
    Molting: "Absent",
  },
  Mollusca: {
    "Specialized tissues": "Present",
    "Body plan symmetry": "Bilateral",
    "Embryonic cell layers": "Triploblastic",
    Coelom: "Eucoelomate",
    "Embryonic development": "Protostome",
    "Digestive system": "One-way",
    Segmentation: "Both",
    Cephalization: "Present",
    Motility: "Sessile",
    Molting: "Absent",
  },
  Arthropoda: {
    "Specialized tissues": "Present",
    "Body plan symmetry": "Bilateral",
    "Embryonic cell layers": "Triploblastic",
    Coelom: "Eucoelomate",
    "Embryonic development": "Protostome",
    "Digestive system": "One-way",
    Segmentation: "Both",
    Cephalization: "Present",
    Motility: "Motile",
    Molting: "Present",
  },
  Nematoda: {
    "Specialized tissues": "Present",
    "Body plan symmetry": "Bilateral",
    "Embryonic cell layers": "Triploblastic",
    Coelom: "Pseudocoelomate",
    "Embryonic development": "Protostome",
    "Digestive system": "One-way",
    Segmentation: "Absent",
    Cephalization: "Present",
    Motility: "Motile",
    Molting: "Present",
  },
  Echinodermata: {
    "Specialized tissues": "Present",
    "Body plan symmetry": "Radial",
    "Embryonic cell layers": "Triploblastic",
    Coelom: "Eucoelomate",
    "Embryonic development": "Deuterostome",
    "Digestive system": "One-way",
    Segmentation: "Absent",
    Cephalization: "None",
    Motility: "Motile",
    Molting: "Absent",
  },
};

export const possibleAnswersForChordates = {
  Skeleton: [
    "No cranium or vertebrae",
    "None",
    "Cartilage, jawless, bony.",
    "Cartilage, braincase, vertebrae",
    "Bony",
  ],
  Limbs: ["No paired fins", "None", "Paired fins", "Paired limbs"],
  Respiration: ["Gills", "Lungs and skin", "Lungs"],
  "Body heat": ["Ectotherm", "Endotherm"],
  Heart: [
    "Only ventral aorta",
    "Simple, no capillaries",
    "Two chambered",
    "Three chambered",
    "Four chambered",
  ],
  "Fertilization and development": [
    "Separate sexes. External fertilization/development",
    "Hermaphrodites. External fertilization/development",
    "Separate sexes. Internal fertilization, external development",
    "Separate/Hermaphrodite. External fertilization/development",
    "Separate sexes. Internal fertilization/development",
  ],
  "Outer covering": [
    "Cuticle layer",
    "Thick tunic",
    "Soft",
    "Scales",
    "Skin",
    "Feathers",
  ],
  "Cephalization complexity": [
    "Small swelling for brain",
    "Larvae have sensory structures.",
    "Eyes and ears",
    "Brain, sense organs",
  ],
};

export const chordateData = {
  Cephalochordata: {
    Skeleton: "No cranium or vertebrae",
    Limbs: "No paired fins",
    Respiration: "Gills",
    "Body heat": "Ectotherm",
    Heart: "Only ventral aorta",
    "Fertilization and development":
      "Separate sexes. External fertilization/development",
    "Outer covering": "Cuticle layer",
    "Cephalization complexity": "Small swelling for brain",
  },
  Urochordata: {
    Skeleton: "None",
    Limbs: "None",
    Respiration: "Gills",
    "Body heat": "Ectotherm",
    Heart: "Simple, no capillaries",
    "Fertilization and development":
      "Hermaphrodites. External fertilization/development",
    "Outer covering": "Thick tunic",
    "Cephalization complexity": "Larvae have sensory structures.",
  },
  Agnatha: {
    Skeleton: "Cartilage, jawless, bony.",
    Limbs: "No paired fins",
    Respiration: "Gills",
    "Body heat": "Ectotherm",
    Heart: "Two chambered",
    "Fertilization and development":
      "Separate sexes. External fertilization/development",
    "Outer covering": "Soft",
    "Cephalization complexity": "Eyes and ears",
  },
  Chondrichthyes: {
    Skeleton: "Cartilage, braincase, vertebrae",
    Limbs: "Paired fins",
    Respiration: "Gills",
    "Body heat": "Ectotherm",
    Heart: "Two chambered",
    "Fertilization and development":
      "Separate sexes. Internal fertilization, external development",
    "Outer covering": "Scales",
    "Cephalization complexity": "Brain, sense organs",
  },
  Osteichthyes: {
    Skeleton: "Bony",
    Limbs: "Paired fins",
    Respiration: "Gills",
    "Body heat": "Ectotherm",
    Heart: "Two chambered",
    "Fertilization and development":
      "Separate/Hermaphrodite. External fertilization/development",
    "Outer covering": "Scales",
    "Cephalization complexity": "Brain, sense organs",
  },
  Amphibia: {
    Skeleton: "Bony",
    Limbs: "Paired limbs",
    Respiration: "Lungs and skin",
    "Body heat": "Ectotherm",
    Heart: "Three chambered",
    "Fertilization and development":
      "Separate sexes. Internal fertilization, external development",
    "Outer covering": "Skin",
    "Cephalization complexity": "Brain, sense organs",
  },
  Reptilia: {
    Skeleton: "Bony",
    Limbs: "Paired limbs",
    Respiration: "Lungs",
    "Body heat": "Ectotherm",
    Heart: "Three chambered",
    "Fertilization and development":
      "Separate sexes. Internal fertilization, external development",
    "Outer covering": "Scales",
    "Cephalization complexity": "Brain, sense organs",
  },
  Aves: {
    Skeleton: "Bony",
    Limbs: "Paired limbs",
    Respiration: "Lungs",
    "Body heat": "Endotherm",
    Heart: "Four chambered",
    "Fertilization and development":
      "Separate sexes. Internal fertilization, external development",
    "Outer covering": "Feathers",
    "Cephalization complexity": "Brain, sense organs",
  },
  Mammalia: {
    Skeleton: "Bony",
    Limbs: "Paired limbs",
    Respiration: "Lungs",
    "Body heat": "Endotherm",
    Heart: "Four chambered",
    "Fertilization and development":
      "Separate sexes. Internal fertilization/development",
    "Outer covering": "Skin",
    "Cephalization complexity": "Brain, sense organs",
  },
};
